[package]
edition = "2021"
name = "xorm_macro"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
async-trait = "0.1.64"
quote = "1.0"
syn = "1.0"
tokio = { version = "1.25.0", features = ["full"] }
tokio-postgres = "0.7.7"
